import { expect, test } from "@playwright/test";
import { chooseStory, clickGame, enterLobby, finishDinner, receiveEnvelope, takeGroupPhoto, returnFromPhoto } from "./story-helpers";

test("only unfinished lobby activities are listed; normal visits unlock the ceremony and dinner", async ({ page }, testInfo) => {
  test.setTimeout(100000);
  await page.setViewportSize({ width: 393, height: 852 });
  await page.goto("/");
  await enterLobby(page);
  const canvas = page.locator("#app canvas");
  await clickGame(page, 360, 460);
  await receiveEnvelope(page);
  await expect(canvas).toHaveAttribute("data-q3-modal-open", "false");
  await expect(canvas).toHaveAttribute("data-reception-complete", "true");
  await clickGame(page, 590, 150);
  await expect(canvas).toHaveAttribute("data-lobby-info", "explore-required");
  await page.locator(".story-narration").click();
  await expect(page.locator(".story-choice")).toHaveCount(2);
  await expect(page.locator(".story-copy")).toContainText("아직 2개의 추억이 남았어요.");
  await page.keyboard.press("Escape");
  await clickGame(page, 550, 450);
  await expect(canvas).toHaveAttribute("data-photo-gallery-open", "true");
  await page.keyboard.press("Escape");
  await clickGame(page, 590, 150);
  await expect(canvas).toHaveAttribute("data-lobby-info", "explore-required");
  await page.locator(".story-narration").click();
  await expect(page.locator(".hall-requirements .story-choice")).toHaveCount(1);
  await expect(page.getByRole("button", { name: "포토테이블 구경하기" })).toHaveCount(0);
  await expect(page.locator(".hall-requirements")).not.toContainText("포토테이블");
  await page.keyboard.press("Escape");
  await clickGame(page, 130, 590);
  await expect(canvas).toHaveAttribute("data-active-scene", "PhotoBoothScene");
  await expect(canvas).toHaveAttribute("data-photo-booth-visited", "false");
  await clickGame(page, 360, 860);
  await expect(canvas).toHaveAttribute("data-photo-booth-visited", "true");
  await returnFromPhoto(page);
  await expect(canvas).toHaveAttribute("data-active-scene", "VenueLobbyScene");
  await expect(canvas).toHaveAttribute("data-lobby-ready", "true");
  await clickGame(page, 590, 150);
  await expect(canvas).toHaveAttribute("data-active-scene", "VenueHallScene");
  await chooseStory(page, "환호를 한다");
  await takeGroupPhoto(page);
  await expect(canvas).toHaveAttribute("data-dinner-stage", "buffet", { timeout: 15000 });
  await expect(canvas).toHaveAttribute("data-buffet-photo-count", "6");
  await clickGame(page, 360, 640);
  await expect(canvas).toHaveAttribute("data-buffet-reveal-complete", "true");
  await expect(page.locator(".buffet-navigation")).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath("buffet-mobile.png") });
  await finishDinner(page);
  await expect(page.locator(".story-narration")).toHaveAttribute("aria-label", /이 브라우저에 저장/);
  await page.getByRole("button", { name: "처음부터 다시" }).click();
  await expect(canvas).toHaveAttribute("data-active-scene", "IntroScene");
  await expect(canvas).toHaveAttribute("data-photo-booth-visited", "false");
  await expect(canvas).toHaveAttribute("data-photo-table-visited", "false");
});
